name: splitml
dependencies: 
  - python == 3.9
  - ipython
  - ipykernel
  - matplotlib
  - numpy >= 1.21
  - pandas >= 1.3
  - pip
  - scipy
  - scikit-learn
  - seaborn
  - statsmodels
  - tqdm
  - pyyaml
  - tensorboard